enum Gender {
  MALE
  FEMALE
}

type Entry {
  firstName: String!
  lastName: String!
  email: String!
  date: String! # need to figure this out
  gender: Gender!
  weight: String! # send in as total oz
}

type Query {
  entries: [Entry!]!
}
