enum Gender {
  MALE
  FEMALE
}

type Entry {
  firstName: String!
  lastName: String!
  email: String!
  date: String!
  gender: Gender!
  weight: String! # total OZ
}

type Query {
  entries: [Entry!]!
}
